name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  incubator:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3.0.3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install all packages
        shell: bash -l {0}
        run: |
          conda activate test
          cd ..
          git clone https://github.com/int-brain-lab/iblapps.git
          pip install --editable iblapps
          cd iblenv
          pip install --requirement requirements.txt
          echo "----- pip list -----"
          pip list
