# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, install_clean_up ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  incubator:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8"]
    steps:
      - name: Clone iblenv repo
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: iblenv
          environment-file: iblenv.yaml
      - shell: bash -l {0}
        run: |
          echo "----- conda activate iblenv -----"
          conda activate iblenv
          echo "----- conda info -----"
          conda info
          echo "----- conda list -----"
          conda list
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "----- pip list -----"
          pip list